version: 2

jobs:
  fetch_dependencies:
    docker:
    - image: ixai/pipenv:3.5
      environment:
        PIPENV_VENV_IN_PROJECT: "true"
    steps:
    - checkout
    - restore_cache:
        keys:
        - pipenv-deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
        - pipenv-deps-{{ .Branch }}
        - pipenv-deps-master
        - pipenv-deps
    - run: pipenv install -d
    - save_cache:
        key: pipenv-deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
        paths:
        - .venv
    - persist_to_workspace:
        root: ./
        paths:
        - .venv
  lint:
    docker:
    - image: ixai/pipenv:3.5
      environment:
        PIPENV_VENV_IN_PROJECT: "true"
    steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: Lint (flake8)
        command: pipenv run lint
  unit_test:
    docker:
    - image: ixai/pipenv:3.5
      environment:
        PIPENV_VENV_IN_PROJECT: "true"
    steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: Unit test (nose)
        command: pipenv run test
  type_check:
    docker:
    - image: python:3.6.4
      environment:
        PIPENV_VENV_IN_PROJECT: "true"
    steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: Type Check (mypy)
        command: pipenv run type_check
    - store_artifacts:
        path: ./.mypy-report

    

workflows:
  version: 2
  continuous_integration:
    jobs:
    - fetch_dependencies
    - lint:
        requires:
        - fetch_dependencies
    - unit_test:
        requires:
        - fetch_dependencies
    - type_check:
        requires:
        - fetch_dependencies
